[
	{
		"key": "dbln",
		"value": "%7B%2261581655850246%22%3A%222NOLW1gL%22%7D",
		"domain": "facebook.com",
		"path": "/login/device-based/",
		"hostOnly": false,
		"creation": "2025-10-07T18:11:07.150Z",
		"lastAccessed": "2025-10-07T18:11:07.150Z"
	},
	{
		"key": "datr",
		"value": "K1HlaD-3jkW6iXuCAcDVHpms",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2025-10-07T18:11:07.150Z",
		"lastAccessed": "2025-10-07T18:11:07.150Z"
	},
	{
		"key": "sb",
		"value": "K1HlaP1zzrSxTS_bSgXPSLJn",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2025-10-07T18:11:07.150Z",
		"lastAccessed": "2025-10-07T18:11:07.150Z"
	},
	{
		"key": "m_pixel_ratio",
		"value": "2",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2025-10-07T18:11:07.150Z",
		"lastAccessed": "2025-10-07T18:11:07.150Z"
	},
	{
		"key": "wd",
		"value": "360x800",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2025-10-07T18:11:07.150Z",
		"lastAccessed": "2025-10-07T18:11:07.150Z"
	},
	{
		"key": "ps_l",
		"value": "1",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2025-10-07T18:11:07.150Z",
		"lastAccessed": "2025-10-07T18:11:07.150Z"
	},
	{
		"key": "ps_n",
		"value": "1",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2025-10-07T18:11:07.150Z",
		"lastAccessed": "2025-10-07T18:11:07.151Z"
	},
	{
		"key": "c_user",
		"value": "61581655850246",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2025-10-07T18:11:07.151Z",
		"lastAccessed": "2025-10-07T18:11:07.151Z"
	},
	{
		"key": "xs",
		"value": "3%3AjYnBYYog3IsPXA%3A2%3A1759859015%3A-1%3A-1",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2025-10-07T18:11:07.151Z",
		"lastAccessed": "2025-10-07T18:11:07.151Z"
	},
	{
		"key": "locale",
		"value": "en_GB",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2025-10-07T18:11:07.151Z",
		"lastAccessed": "2025-10-07T18:11:07.151Z"
	},
	{
		"key": "pas",
		"value": "61581655850246%3AgFFiawam0M",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2025-10-07T18:11:07.151Z",
		"lastAccessed": "2025-10-07T18:11:07.151Z"
	},
	{
		"key": "vpd",
		"value": "v1%3B668x360x2",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2025-10-07T18:11:07.151Z",
		"lastAccessed": "2025-10-07T18:11:07.151Z"
	},
	{
		"key": "fr",
		"value": "04kTUTzA3bFhXq630.AWfU1egpGcr0COlWmHupugdqS5xgX3LKtKBBFF9keOhNmUGjtdo.Bo5VEr..AAA.0.0.Bo5Vdt.AWcnbsesdYM8uGEFhaQb2UTyUHM",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2025-10-07T18:11:07.151Z",
		"lastAccessed": "2025-10-07T18:11:07.151Z"
	},
	{
		"key": "fbl_st",
		"value": "101424970%3BT%3A29331009",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2025-10-07T18:11:07.151Z",
		"lastAccessed": "2025-10-07T18:11:07.151Z"
	},
	{
		"key": "wl_cbv",
		"value": "v2%3Bclient_version%3A2947%3Btimestamp%3A1759860589",
		"domain": "facebook.com",
		"path": "/",
		"hostOnly": false,
		"creation": "2025-10-07T18:11:07.151Z",
		"lastAccessed": "2025-10-07T18:11:07.151Z"
	}
]
